export const tempName = {
  firstName: "",
  lastName: "",
  accountNo: "",
  email: "",
  drivingLicense: "",
  dateOfBirth: null,
  dateOfDeath: null,
  cellPhone: null,
  homePhone: null,
  workPhone: null,
  ext: null,
  address: "",
  zipCode: "",
  emergencyContactFirstName: "",
  emergencyContactLastName: "",
  emergencyContactAddress: "",
  emergencyContactZipCode: "",
  emergencyContactState: "",
  emergencyContactCity: "",
  // dateOfDeath: null,
  // dropdowns
  genderIdentityName: "",
  maritalStatusName: "",
  raceStatusName: "",
  sexualOrientationName: "",
  employmentStatusName: "",
  referralSourceName: "",
  relationShipToPatientName: "",
  ethnicityName: "",
  studentStatusName: "",
  accountType: "",
  cityName: "",
  countryName: "",
  stateName: "",
  residenceTypeName: "",

  // Insured Information Data
  insuredFirstName: "",
  insuredLastName: "",
  insuredDateOfBirth: null,
  insuredAddress: "",
  insuredSSN: "",
  insuredZipCode: "",
  insuredHomePhone: null,
  insuredCellPhone: null,
  insuredWorkPhone: null,
  insuredExt: null,
  insuredEmail: "",
  insuredCityName: "",
  insuredStateName: "",
  insuredCountryName: "",
  insuredRelationShipToPatientName: "",
  insuredGenderIdentityName: "",
  // employeeName: "",
  empAddress: "",
  empCityName: "",
  empStateName: "",
  insuredPartyName: "",
  empZipCode: "",
  empEmploymentStatusName: "",

  // patientName: "",

  // payer info data
  payerInfoMemberId: null,
  payerInfoGroupId: null,
  payerInfoCopayAmount: null,
  payerInfoCoInsurancePercent: null,
  payerInfoDeductibleAmount: null,
  payerInfoOutOfPocketMax: null,
  payerInfoEffectiveDate: null,
  payerInfoTerminationDate: null,
  payerInfoPriorityName: "",
  payerInfoPolicyType: "",
  payerInfoPayerName: "",
};
