export const patientInitValues = {
  firstName: "",
  lastName: "",
  // patientAccountNo: null,
  accountNo: null,
  email: "",
  drivingLicense: "",
  dateOfBirth: null,
  dateOfDeath: null,
  cellPhone: null,
  homePhone: null,
  workPhone: null,
  ext: null,
  address: "",
  zipCode: "",
  emergencyContactFirstName: "",
  emergencyContactLastName: "",
  emergencyContactAddress: "",
  emergencyContactZipCode: "",
  emergencyContactState: "",
  emergencyContactCity: "",
  // dateOfDeath: null,
  // dropdowns
  genderIdentityName: "",
  maritalStatusName: "",
  raceStatusName: "",
  sexualOrientationName: "",
  employmentStatusName: "",
  referralSourceName: "",
  relationShipToPatientName: "",
  ethnicityName: "",
  studentStatusName: "",
  accountType: "",
  cityName: "",
  countryName: "",
  stateName: "",
  residenceTypeName: "",

  // Insured Information Data
  insuredFirstName: "",
  insuredLastName: "",
  insuredDateOfBirth: null,
  insuredAddress: "",
  insuredSSN: "",
  insuredZipCode: "",
  insuredHomePhone: null,
  insuredCellPhone: null,
  insuredWorkPhone: null,
  insuredExt: null,
  insuredEmail: "",
  insuredCityName: "",
  insuredStateName: "",
  insuredCountryName: "",
  insuredRelationShipToPatientName: "",
  insuredGenderIdentityName: "",
  insuredPriorityType: "",
  // employeeName: "",
  empAddress: "",
  empCityName: "",
  empStateName: "",
  insuredPartyName: "",
  empZipCode: "",
  empEmploymentStatusName: "",
  // payer info data
  payerInfoMemberId: null,
  payerInfoGroupId: null,
  payerInfoCopayAmount: null,
  payerInfoCoInsurancePercent: null,
  payerInfoDeductibleAmount: null,
  payerInfoOutOfPocketMax: null,
  payerInfoEffectiveDate: null,
  payerInfoTerminationDate: null,
  payerInfoPriorityName: "",
  payerInfoPolicyType: "",
  payerInfoPayerName: "",
  payerInfoSequenceNumber: null,
};

export const claimInitVal = {
  patientName: "",
  patientAccountNo: null,
  renderingProviderName: "",
  billingProviderName: "",
  supervisingProviderName: "",
  practiceAddress: "",
  practiceSequenceNo: null,
  primaryPayerInsuranceName: "",
  primaryPayerMemberId: null,
  primaryPayerGroupId: null,
  primaryPayerPolicyType: "",
  primaryPayerCopayDue: null,
  // payerSequenceNo: null,
  claimFrequency: "",
  referenceNumber: null,
  facilityName: "",
  claimType: "Professional",
  // tcn: "abc",
  // totalCharges: 200,
  // totalBilled: 200,

  // claim diagnosis id
  icD_A: null,
  icD_B: null,
  icD_C: null,
  icD_D: null,
  icD_E: null,
  icD_F: null,
  icD_G: null,
  icD_H: null,
  icD_I: null,
  icD_J: null,
  icD_K: null,
  icD_L: null,

  // claim diagnosis name
  icD_Code_A: "",
  icD_Code_B: "",
  icD_Code_C: "",
  icD_Code_D: "",
  icD_Code_E: "",
  icD_Code_F: "",
  icD_Code_G: "",
  icD_Code_H: "",
  icD_Code_I: "",
  icD_Code_J: "",
  icD_Code_K: "",
  icD_Code_L: "",

  // description
  icd_Description_A: "",
  icd_Description_B: "",
  icd_Description_C: "",
  icd_Description_D: "",
  icd_Description_E: "",
  icd_Description_F: "",
  icd_Description_G: "",
  icd_Description_H: "",
  icd_Description_I: "",
  icd_Description_J: "",
  icd_Description_K: "",
  icd_Description_L: "",
};

// export const paymentInitValue = {
//   isClaim: true,
//   isPatientPayment: false,
//   paymentBy: "",
//   payerSequenceNo: null,
//   payerId: null,
//   payerName: "",
//   paymentFrom: null,
//   paymentFromName: "",
//   paymentAmount: null,
//   checkDate: null,
//   checkNumber: "",
//   patientAccountNo: null,
//   patientId: null,
//   isCopay: false,
//   copayServiceDate: null,
//   memo: "",
//   claimNumber: null,
//   claimInfoId: null,
//   creditCardType: "",
//   paymentMethod: "check",
//   patientFirstName: "",
//   patientLastName: "",
//   tcn: "",
//   dateOfService: null,
//   providerId: null,
//   billed: 0,
//   allowed: 0,
//   paid: 0,
//   unpaid: 0,
//   adjusted: 0,
//   additionalActions: 0,
//   balance: 0,
//   isRemove: false,
//   procedureCodes: "",
//   amount: 0,
//   startBalance: 0,
//   deductible: null,
//   claimStatus: "",
//   otherCredits: null,
//   endBalanace: 0,
//   claimChargesDto: [],
//   applied: 0,
// };

// export const paymentInitValue2 = {
//   isClaim: true,
//   isPatientPayment: false,
//   paymentBy: "",
//   payerSequenceNo: null,
//   payerId: null,
//   payerName: "",
//   paymentFrom: null,
//   paymentFromName: "",
//   paymentAmount: null,
//   checkDate: null,
//   checkNumber: "",
//   patientAccountNo: null,
//   patientId: null,
//   isCopay: false,
//   copayServiceDate: null,
//   memo: "",
//   claimNumber: null,
//   claimInfoId: null,
//   creditCardType: "",
//   paymentMethod: "check",
//   patientFirstName: "",
//   patientLastName: "",
//   tcn: "",
//   dateOfService: null,
//   providerId: null,
// };

export const paymentInitVal3 = {
  isClaim: true,
  isPatientPayment: false,
  payerSequenceNo: null,
  payerId: null,
  paymentFrom: null,
  paymentFromName: "",
  paymentBy: "",
  payerName: "",
  paymentAmount: 0,
  checkDate: null,
  checkNumber: "",
  isCopay: false,
  copayServiceDate: null,
  memo: "",
  eftNumber: null,
  paymentMethod: "",
  creditCardType: "",
  providerId: null,
  providerName: "",
  sequenceNo: null,
  totalPaymentReceived: 0,
  applied: 0,
};
